GET http://localhost:3005/orders

###

POST  http://localhost:3005/orders
Content-Type: application/json

{
    "products_ordered": [{"quantity": 2,
    "product_id": 3}, {"quantity": 1,
    "product_id": 1}], 
    "payment": "efectivo" 
}

###
GET http://localhost:3005/orders/49
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX25hbWUiOiJhZG1pbjMiLCJwYXNzd29yZCI6IiQyYiQwNCQyaFpGRk1LRVhzenozRnd2OVJiNWouM21KcWJVSmtYUm95eUlueEdoYWxQZmpxbDNhR0NERyIsInJvbGUiOiJhZG1pbiJ9.aHb3b1MGtecTp6Ynhj0MaUIsRfmi_mPUR99ZwB_W3q0

###
PUT http://localhost:3005/orders/4
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJyb2xlIjoiY2xpZW50In0.g38kQGSW2xnfU6Oz4HfHyTajqlkPUoHZOOtgfVYVqPY
Content-Type: application/json

{
    "order_status": "confirmado"
}

###

POST  http://localhost:3005/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo1LCJyb2xlIjoiY2xpZW50In0.g38kQGSW2xnfU6Oz4HfHyTajqlkPUoHZOOtgfVYVqPY
Content-Type: application/json

{
    "payment": "efectivo",
    "products_ordered": [
        {"quantity": 2,
        "product_id": 3}, 
        {"quantity": 1,
        "product_id": 1}
        ] 
}


###
DELETE http://localhost:3005/orders/4
