# ----------Orders request---------

# ----------Users request---------

### ---Client loggin
POST http://localhost:3005/login
Content-Type: application/json

{
    "user_name": "ana123", 
    "password": "constraseñ"
}

### ---Admin loggin
POST http://localhost:3005/login
Content-Type: application/json

{
    "user_name": "admin3", 
    "password": "admin"
}


@clientToken = 
@adminToken = 


# -----Create new order-----

### ---No autenthicated
POST  http://localhost:3005/orders
Content-Type: application/json

{
    "payment": "efectivo",
    "products_ordered": [
        {"quantity": 2,
        "product_id": 2}, 
        {"quantity": 1,
        "product_id": 1}
        ] 
}

### ---Client role
POST  http://localhost:3005/orders
Authorization: Bearer {{clientToken}}
Content-Type: application/json

{
    "payment": "efectivo",
    "products_ordered": [
        {"quantity": 2,
        "product_id": 1}, 
        {"quantity": 1,
        "product_id": 2}
        ] 
}

### ---Admin role
POST  http://localhost:3005/orders
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "payment": "efectivo",
    "products_ordered": [
        {"quantity": 2,
        "product_id": 2}, 
        {"quantity": 1,
        "product_id": 1}
        ] 
}

# -----See all orders-----

###---No autenthicated
GET http://localhost:3005/orders

### ---Client role
GET http://localhost:3005/orders
Authorization: Bearer {{clientToken}}

### ---Admin role
GET http://localhost:3005/orders
Authorization: Bearer {{adminToken}}

# -----See one order-----

### ---No autenthicated
GET http://localhost:3005/orders/2

### ---Client role
GET http://localhost:3005/orders/2
Authorization: Bearer {{clientToken}}

### ---Admin role
GET http://localhost:3005/orders/1
Authorization: Bearer {{adminToken}}

# -----See own order-----

### ---No autenthicated
GET http://localhost:3005/orders/2

### ---Client role
GET http://localhost:3005/orders/1
Authorization: Bearer {{clientToken}}

### ---Admin role
GET http://localhost:3005/orders/2
Authorization: Bearer {{adminToken}}


# -----Modify status of one order-----

### ---No autenthicated
PUT  http://localhost:3005/orders/1
Content-Type: application/json

{
    "order_status": "confirmado"
}

### ---Client role
PUT  http://localhost:3005/orders/1
Authorization: Bearer {{clientToken}}
Content-Type: application/json

{
    "order_status": "confirmado"
}

### ---Admin role
PUT  http://localhost:3005/orders/1
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "order_status": "confirmado"
}
