GET http://localhost:3005/products

###

POST  http://localhost:3005/products 
Content-Type: application/json


{
    "product_code": "HamVegglggg",
    "product_name": "Hamburguesa vegana",
    "price": "400"
}

###

GET http://localhost:3005/products/HamVeggg

###

PUT http://localhost:3005/products/HamVeggg
Content-Type: application/json

{
    "product_name": "Hamburguesa vegane",
    "price": "450"    
}

###

DELETE http://localhost:3005/products/HamVeggggg