# ----------Register request---------

### ---Register Client
POST http://localhost:3005/register
Content-Type: application/json

{
    "user_name": "ana123", 
    "name": "Ana Mora",
    "email": "lali@gmail.com",
    "phone": 1174378291,
    "address": "calle falsa 123",
    "password": "constraseñ",
    "role": "client"
}

### ---Register Admin
POST http://localhost:3005/register
Content-Type: application/json

{
    "user_name": "admin3", 
    "name": "Sofía Sanchez",
    "email": "admin@delilahresto.com",
    "phone": 1156785432,
    "address": "calle falsa 321",
    "password": "admin",
    "role": "admin"
}



# ----------Login request---------

### ---No autenthicated
POST http://localhost:3005/login
Content-Type: application/json

{
    "user_name": "fake", 
    "password": "fake"
}

### ---Client role
POST http://localhost:3005/login
Content-Type: application/json

{
    "user_name": "ana123", 
    "password": "constraseñ"
}

### ---Admin role
POST http://localhost:3005/login
Content-Type: application/json

{
    "user_name": "admin3", 
    "password": "admin"
}
